fw:
  asn: 65250
  router_id: 10.250.250.250
  peers:
    VRF-PLATFORM:
      neighbor: 172.20.0.51
      remote_as: 65101
      allow_default: true
    TENANT-042:
      neighbor: 172.20.0.52
      remote_as: 65101
      allow_default: true
    VRF-STORAGE:
      neighbor: 172.20.0.53
      remote_as: 65102
      allow_default: true
